#!/bin/sh
#
#   set multipath with handle
#
#   This program is free software; you can redistribute it and/or modify it under the 
#   terms of the GNU General Public License as published by the Free Software Foundation;
#   either version 3 of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
#   without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#   See the GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License along with this program; 
#   if not, see <http://www.gnu.org/licenses/>.
#
multipath="none"

ver="1.0.2 - 23.2.2016"
retc=0
ls="  "
progname=${0##*/}
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]; do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
export progdir="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
if [ -z $fsifunc ]; then export fsifunc="/usr/bin/fsifunc.sh"; fi
if [ -f $fsifunc ]; then
   . $fsifunc
   . $fsivars
else
   echo "ERROR cannot load fsi functions $fsifunc"
   exit 99
fi
if [ -z $logfile ]; then logfile=$fsidir"/"$progname".log"; fi


function help() {
   echo
   tput setaf 2
   echo " Help for $progname - $ver"    
   tput sgr0

   echo
}


infmsg "Start $progname - $ver"

if [ "$multipath" != "none" ] ; then
   infmsg "$ls  enable multipath with handle: $multipath"

   if [ $retc -eq 0 ]; then
      infmsg "$ls  get host uuid"
      hostuuid=$(xe host-list name-label=$(hostname -s) --minimal)
      retc=$?
      if [ $retc -ne 0 ]; then
         warnmsg "$ls cannot get host uuid - abort"
      fi
   fi
   
   if [ $retc -eq 0 ]; then
      infmsg "$ls  set multipath = true"
      xe host-param-set other-config:multipathing=true uuid=$hostuuid
      retc=$?
      if [ $retc -ne 0 ]; then
         warnmsg "$ls cannot set multipath - abort"
      fi
   fi
   
   if [ $retc -eq 0 ]; then
      infmsg "$ls  set multipath handler to $multipath"
      xe host-param-set other-config:multipathhandle=$multipath uuid=$hostuuid
      retc=$?
      if [ $retc -ne 0 ]; then
         warnmsg "$ls cannot set multipath handler - abort"
      fi
   fi
else
   infmsg "$ls no multipath handler configure - ignore"
fi

infmsg "End $progname rc=$retc"
exit $retc
