#!/bin/sh
#
#   vi toolstack wait
#
#   This program is free software; you can redistribute it and/or modify it under the 
#   terms of the GNU General Public License as published by the Free Software Foundation;
#   either version 3 of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
#   without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#   See the GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License along with this program; 
#   if not, see <http://www.gnu.org/licenses/>.
#
warte=20
count=0
abbruch=15
stack="offline"

ver="1.0.2 - 14.10.2013"
retc=0
ls="  "
progname=${0##*/}
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]; do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
export progdir="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
if [ -z $fsifunc ]; then export fsifunc="/usr/bin/fsifunc.sh"; fi
if [ -f $fsifunc ]; then
   . $fsifunc
   . $fsivars
else
   echo "ERROR cannot load fsi functions $fsifunc"
   exit 99
fi
if [ -z $logfile ]; then logfile=$fsidir"/"$progname".log"; fi


echo -n $(date +%H:%M:%S)" INFO   : $ls  Waiting for XE stack ."

while [ "$stack" == "offline" ]; do
   # flags=$(2>&1 ls -t --full-time /var/run/xapi*)
   # echo "Vor xe Befehl: [$flags]" >> $fsidir/xapi-debug.log
   toolstackstatus=`2>&1 xe host-list name-label=$HOSTNAME --minimal`
   retc=$?
   # flags=$(2>&1 ls -t --full-time /var/run/xapi*)
   # echo "Nach xe Befehl: [$flags]" >> $fsidir/xapi-debug.log
   if [ $retc -ne 0 ] ; then
      if [ $count -le $abbruch ] ; then
         echo -n "."   
         sleep $warte
         count=$((count+1))
      else
         stack="failed - to much retries."
         retc=99
      fi
   else
      stack="online"
   fi
done

echo " $stack"

exit $retc

